version: '3'

services:
    # Frontend
    indiemakers:
        container_name: indiemakers
        image: riderx/indiemakers:latest
        restart: unless-stopped
        environment:
            - PORT=80
            - BOT_TOKEN
            - FIREBASE_DATABASE
            - FIREBASE_ADMIN_KEY
            - CLIENT_PUBLIC_KEY
            - IMAGEKIT_KEY
            - GOOGLE_SERVICE_ACCOUNT
            - DEPLOY_API_ONLY
        networks:
            - net_lemverse

networks:
    net_lemverse:
        external: true
        name: net_lemverse
