version: "3.8"
services:
    mongodb:
        image: mongo
        container_name: mongodb
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - db:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped
        networks:
            - net_lemverse
    lemverse:
        image: riderx/lemverse:latest
        container_name: lemverse
        restart: unless-stopped
        networks:
            - net_lemverse
        depends_on:
            - mongodb
            - peer
        ports:
            - '3000:3000'
        volumes:
            - lemverse:/var/tmp/lemverse
        environment:
            ROOT_URL: ${APP_ROOT_URL:-http://localhost}
            MONGO_URL: mongodb://mongodb:27017/meteor
            PORT: 3000
            METEOR_SETTINGS: |
                {
                    "public": {
                        "lp": {
                            "product": "lemverse",
                            "process": "main",
                            "admins": [],
                            "production": false,
                            "staging": false,
                            "enableLogClient": false
                        },

                        "debug": false,

                        "defaultReaction": "❤️",

                        "zoom": 1,

                        "peer": {
                            "answerMaxAttempt": 5,
                            "answerDelayBetweenAttempt": 750,
                            "avatars": [
                                "https://www.monchat.ca/wp-content/uploads/2020/01/Fond-ecran-mignon-chaton-en-position-de-priere-1024x640.jpg",
                                "https://animalaxy.fr/wp-content/uploads/2019/02/iStock5.jpg",
                                "https://cdn.radiofrance.fr/s3/cruiser-production/2018/12/9f19b228-269f-4995-ba7f-eda054945811/1136_gettyimages-155607257.jpg",
                                "https://chatfaitdubien.fr/wp-content/uploads/2016/09/chaton.jpg",
                                "https://i.pinimg.com/564x/8b/f7/c6/8bf7c6e26f7250944e963f23f364b68f.jpg"
                            ],
                            "callDelay": 250
                        },

                        "meet": {
                            "serverURL": "jitsi.indiemakers.space",
                            "roomDefaultName": "lemverse-test"
                        },

                        "character": {
                            "walkSpeed": 180,
                            "runSpeed": 720
                        },

                        "characterNames": ["Basic", "Ghost"],

                        "skins": {
                            "guest": "Ghost",
                            "default": "Basic"
                        },

                        "templateLevelId": "lvl_iLOVEaLOTlemverse"
                    },

                    "defaultLevelId": "lvl_iLOVEaLOTlemverse",

                    "peer": {
                        "startServer": false,
                        "server": {
                        "url": "localhost",
                        "port": 9000,
                        "path": "/myapp",
                        "credentialDuration": 86400,
                        "secret": "",
                        "config": {
                            "iceServers": [{ 
                            "urls": "stun:stun.l.google.com:19302"
                            }],
                            "sdpSemantics": "unified-plan"
                        }
                        }
                    }
                }

    peer:
        image: peerjs/peerjs-server
        container_name: peer
        restart: unless-stopped
        networks:
            - net_lemverse
        ports:
            - 9000:9000
volumes:
    lemverse:
        driver: local 
    db:
        driver: local
    
# Custom network so all services can communicate using a FQDN
networks:
    net_lemverse:
        driver: bridge
        name: net_lemverse